# Generated by Django 5.1.2 on 2024-10-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='example',
            table='example',
        ),
    ]
